### PR TITLE
CLI Migration to Declarative style and rework of core

### PR DESCRIPTION
**Pull request by ripytide**
Again Apologies for the large PR but this is as small/atomic a PR as I could manage. This PR is based on #73 so #73 would need to be merged before this.

- Cli parsing code now redundant as this automagically done by `clap` now
- `core` module reworked to be based on the new declarative Cli argument types
- switches groups from `HashSet` to `BTreeSet` for built-in sorting/more deterministic general operation
- refactored code base into a global type synonym `Groups` to remove duplication of the `HashSet/BTreeSet` implementation detail to a single location

### CODE REVIEW

**Comment by steven-omaha** [comment]
Do you want to rebase your PR against the latest HEAD?

**Comment by ripytide** [comment]
I though I had done so already, what method did you use to merge the last pull request? It seems to have added a second duplicate commit?

**Comment by steven-omaha** [comment]
I have done it via the GH web interface.

**Comment by steven-omaha** [comment]
Yeah, that rebase fixed it. Thanks.

**Comment by ripytide** [comment]
In the dropdown which merge method did you select? In the default option I don't think it should create such duplicate commits.

**Comment by steven-omaha** [comment]
I used the first one indeed. ("merge pull requst")

**Comment by ripytide** [comment]
Odd, well anyway its fixed now

**Review by steven-omaha — APPROVED** [review]
Well done! I love how core.rs is a lot more readable now; that bothered me for a long time.

Thank you!

**Pull request merged**
