### PR TITLE
Release action to build binary

### PR DESCRIPTION
**Pull request by thechubbypanda**
Action will build binary on release and attach the resulting zip to the release.

[Example release](https://github.com/thechubbypanda/pacdef/releases/tag/0.0.1-alpha)

[Related Actions run](https://github.com/thechubbypanda/pacdef/actions/runs/8434849647)

Part of #58

### CODE REVIEW

**Comment by steven-omaha** [comment]
Thank you, looking good so far!

I have little expertise in Github Actions. From what I can see this built pacdef without any feature flags on Debian against the latest stable musl-based toolchain. It produced an artifact that it attached to the release. 

That is a very good start. What would be great to have is that it produces one artifact for every [backend that requires a feature flag](https://github.com/steven-omaha/pacdef?tab=readme-ov-file#supported-backends). At the moment three artifacts would have to be built: one without any flags (which you completed), one for Arch (`cargo build --release --features arch`), and one for Debian (`--features debian`). Then the user can download whatever he needs. That would also enable me to easily maintain a `pacdef-bin` AUR package for Arch. 

The reason for the feature flags is that these backends need to be built and linked against a specific version of the package manager. 

Is it possible to add this? I think I remember some matrix can be specified to build multiple things with varying configurations.

And it may be reasonable to build on an Arch runner if there is one, for the reason that the latest version of libalpm is probably not available on Debian (required for arch), but the latest apt is available on Arch.

FYI, the Debian backend is currently borked due to a new release of rust-apt. See #64.

**Comment by thechubbypanda** [comment]
Yep, that makes sense to me, I'll see about matrix'ing the features into different packages

**Comment by thechubbypanda** [comment]
@steven-omaha Any idea what [this](https://github.com/thechubbypanda/pacdef/actions/runs/8470379164/job/23207955180) is about? 

The other 2 are building nicely: https://github.com/thechubbypanda/pacdef/releases/tag/0.0.11-alpha

**Review by steven-omaha — CHANGES_REQUESTED** [review]
I can confirm this all works nicely. Thank you and well done!

I have two minor things to ask for: the man pages and the folder structure. 

Currently when I extract the tar file it spills its content in the workdir. When the workdir is not empty its hardly possible to see what was extracted. AFAIK the convention in Linux is to extract it in a subdir.

```
$ ls
pacdef-default.tar.gz
$ tar -xf pacdef-default.tar.gz
$ ls
LICENSE  pacdef-default.tar.gz  README.md  target
```

Could you please make it so that after untarring the following structure is created?

```
$ ls
pacdef-default.tar.gz  pacdef-default
$ ls pacdef-default
pacdef  LICENSE  README.md  man
$ ls pacdef-default/man
pacdef.8  pacdef.yaml.5
```

Once that is done, I can merge it.

Thanks again, and good job!

**Comment by thechubbypanda** [comment]
Should follow your suggested structure now:
https://github.com/thechubbypanda/pacdef/releases/tag/0.0.14-alpha

**Review by steven-omaha — APPROVED** [review]
LGTM. Thank you, merging!

**Comment by steven-omaha** [comment]
FYI, I'm still testing the new rustup backend that I merged today. Once I'm satisfied this works I will release a new version 1.5.0 where the binaries are distributed as well.

**Pull request merged**
